### ISSUE TITLE
Issue with JSX

### ISSUE THREAD

**Issue by razagill** [idok/jscs-plugin#11]
So right now, the plugin works fine unless you have JSX pages. Is there a way we can bypass JSX checking in reactjs components?

**Comment by idok** [comment]
Hi,
JSCS plugin runs JSCS command line, so you need to check with the docs if they support JSX.
http://jscs.info/overview.html

**Comment by razagill** [comment]
They do with the `--esprima` flag set to `fb`. From their docs, "Attempts to parse your code with a custom Esprima version."
`jscs path[ path[...]] --esprima=esprima-fb`

Is there a way we can configure this in the plugin?

**Comment by idok** [comment]
add esprima option, will be available soon in version 1.0.3
