### ISSUE TITLE
JSCS: Can not find 'jscs' script file under JSCS package directory

### ISSUE THREAD

**Issue by arnaugm** [idok/jscs-plugin#22]
The plugin doesn't seem to detect correctly the script in the path in PhpStorm 9.
I set the "JSCS package" field to the bin folder that contains the script.

PhpStorm 9.0
jscs plugin 1.0.5

**Comment by carltondickson** [comment]
I did the same as you but it doesn't detect the jscs file in the folder on windows.

So I ended up entering the exact path to the file

C:\Users\my_user\AppData\Roaming\npm\node_modules\jscs\bin\jscs

**Comment by arnaugm** [comment]
I'm using Ubuntu.
Apparently the requested folder in this case is the jscs folder under node_modules, not the bin folder.

**Comment by liuxing95** [comment]
how to solute this question? who can answer, please contact me thanks
